# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20160527_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(default='WPIERDOL', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
