# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
